version: 0.2

env:
  variables:
    SAM_CLI_TELEMETRY: 0
    TZ: Australia/Sydney
    NODE_INSTALL_URL: https://nodejs.org/dist/latest-v20.x
    APP_CONFIG_GROUP_PREFIX: ${configGroupPrefix}

phases:
  install:
    commands:
      - date
      - cd /tmp
      - export NODE_FILE_NAME=$(curl -s $NODE_INSTALL_URL/ | grep 'linux-arm64.tar.gz' | awk -F '"' '{print $2}')
      - wget -q $NODE_INSTALL_URL/$NODE_FILE_NAME
      - wget -q $NODE_INSTALL_URL/SHASUMS256.txt
      - grep $NODE_FILE_NAME SHASUMS256.txt | sha256sum -c -
      - tar -xf $NODE_FILE_NAME
      - export NODE_NAME=$(basename $NODE_FILE_NAME .tar.gz)
      - PATH="/tmp/$NODE_NAME/bin:$PATH"
      - npm install -g aws-cdk@2

  build:
    commands:
      - date
      - mkdir -p $HOME/.gradle
      - echo 'org.gradle.console=plain' > $HOME/.gradle/gradle.properties
      - echo 'org.gradle.daemon=false' >> $HOME/.gradle/gradle.properties
      - cd $CODEBUILD_SRC_DIR_Artifact_Checkout_Source_GitHub_CI_CD_Source
      - export APP_CONFIG_ROOT_CONFIG_FOLDER=$CODEBUILD_SRC_DIR
      - cdk --no-color --ci --require-approval=never deploy
      - date
      - cd build/distributions
      - tar -xf application-configuration-store-cicd.tar
      - cd $CODEBUILD_SRC_DIR_Artifact_Checkout_Source_GitHub_CI_CD_Source
      - java -Dapp.config.root.config.folder=$CODEBUILD_SRC_DIR -Dapp.config.group.prefix=$APP_CONFIG_GROUP_PREFIX -cp "build/distributions/application-configuration-store-cicd/lib/*" org.example.UpdateConfigProfile
      - date
      - java -Dapp.config.group.prefix=$APP_CONFIG_GROUP_PREFIX -cp "build/distributions/application-configuration-store-cicd/lib/*" org.example.DeployConfigProfile
