version: 0.2

env:
  variables:
    SAM_CLI_TELEMETRY: 0
    TZ: Australia/Sydney
    NODE_NAME: node-v20.15.1-linux-arm64
    APP_CONFIG_GROUP_PREFIX: ${configGroupPrefix}

phases:
  install:
    commands:
      - date
      - cd /tmp
      - export NODE_FILE_NAME=$NODE_NAME.tar.gz
      - wget -q https://nodejs.org/dist/v20.15.1/$NODE_FILE_NAME
      - echo "8554c91ccd32782351035d3a9b168ad01c6922480800a21870fc5d6d86c2bb70  $NODE_FILE_NAME" > SHASUMS256.txt
      - grep $NODE_FILE_NAME SHASUMS256.txt | sha256sum -c -
      - tar -xf $NODE_FILE_NAME
      - PATH="/tmp/$NODE_NAME/bin:$PATH"
      - npm install -g aws-cdk@2

  build:
    commands:
      - date
      - mkdir -p $HOME/.gradle
      - echo 'org.gradle.console=plain' > $HOME/.gradle/gradle.properties
      - echo 'org.gradle.daemon=false' >> $HOME/.gradle/gradle.properties
      - cd $CODEBUILD_SRC_DIR_Artifact_Checkout_Source_GitHub_CI_CD_Source
      - export APP_CONFIG_ROOT_CONFIG_FOLDER=$CODEBUILD_SRC_DIR
      - cdk --no-color --ci --require-approval=never diff
      - date
      - cd build/distributions
      - tar -xf application-configuration-store-cicd.tar
      - cd $CODEBUILD_SRC_DIR_Artifact_Checkout_Source_GitHub_CI_CD_Source
      - java -Dapp.config.root.config.folder=$CODEBUILD_SRC_DIR -Dapp.config.group.prefix=$APP_CONFIG_GROUP_PREFIX -cp "build/distributions/application-configuration-store-cicd/lib/*" org.example.DiffConfigProfile

artifacts:
  files:
    - '**/*'
